[
  {
    wrt: {
      wort: "Psychologie",
      plural: "Psychologie",
      prefix: "",
      suffix: "",
      artikel: "die",
    },
    fall: {
      Dativobjekt: "",
      Akkusativobjekt: "",
      Reflexivpronomen: "",
      Other: "",
    },
    status: {
      Deklination: "Deklination",
      Zertifikat: "C2",
      Substantiv: "Substantiv",
      Adjektiv: "",
      Superlativ: "",
      Komparativ: "",
      Plural: "-",
      Positiv: "",
      Genus: "feminin",
      gesteigert: "",
      regelmäßige: "unregelmäßig",
      Artikel: "",
      starke: "",
      Pronomen: "",
      Other: "",
    },
    theme: "",
    source: "",
    main_Html: "die <b><i></i>Psycho<i></i>logie<i></i></b>",
    main_Sound:
      "https://www.verbformen.de/deklination/substantive/grundform/der_Psychologie.mp3",
    sub_Html: "die -",
    sub_Sound:
      "https://www.verbformen.de/deklination/substantive/stammformen/der_Psychologie.mp3",
    lang_TR: " ruh bilimi, psikoloji",
    lang_DE: "",
    tbl: { prasens: "", praterium: "", perfekt: "" },
  },
  {
    wrt: {
      wort: "Garage",
      plural: "Garagen",
      prefix: "",
      suffix: "",
      artikel: "die",
    },
    fall: {
      Dativobjekt: "",
      Akkusativobjekt: "",
      Reflexivpronomen: "",
      Other: "",
    },
    status: {
      Deklination: "Deklination",
      Zertifikat: "A2",
      Substantiv: "Substantiv",
      Adjektiv: "",
      Superlativ: "",
      Komparativ: "",
      Plural: "-en",
      Positiv: "",
      Genus: "feminin",
      gesteigert: "",
      regelmäßige: "regelmäßig",
      Artikel: "",
      starke: "",
      Pronomen: "",
      Other: "",
    },
    theme: "",
    source: "",
    main_Html: "die <b><i></i>Garage<i></i></b>",
    main_Sound:
      "https://www.verbformen.de/deklination/substantive/grundform/der_Garage.mp3",
    sub_Html: "die <b><i></i>Garage<i>n</i></b>",
    sub_Sound:
      "https://www.verbformen.de/deklination/substantive/stammformen/der_Garage.mp3",
    lang_TR: "garaj",
    lang_DE: "",
    tbl: { prasens: "", praterium: "", perfekt: "" },
  },
  {
    wrt: {
      wort: "Fahrt",
      plural: "Fahrten",
      prefix: "",
      suffix: "",
      artikel: "die",
    },
    fall: {
      Dativobjekt: "",
      Akkusativobjekt: "",
      Reflexivpronomen: "",
      Other: "",
    },
    status: {
      Deklination: "Deklination",
      Zertifikat: "A1",
      Substantiv: "Substantiv",
      Adjektiv: "",
      Superlativ: "",
      Komparativ: "",
      Plural: "-en",
      Positiv: "",
      Genus: "feminin",
      gesteigert: "",
      regelmäßige: "regelmäßig",
      Artikel: "",
      starke: "",
      Pronomen: "",
      Other: "",
    },
    theme: "",
    source: "",
    main_Html: "die <b><i></i>Fahrt<i></i></b>",
    main_Sound:
      "https://www.verbformen.de/deklination/substantive/grundform/der_Fahrt.mp3",
    sub_Html: "die <b><i></i>Fahrt<i>en</i></b>",
    sub_Sound:
      "https://www.verbformen.de/deklination/substantive/stammformen/der_Fahrt.mp3",
    lang_TR: "tur, seyahat, yolculuk, gidiş, gitme, hız, sürat",
    lang_DE: "",
    tbl: { prasens: "", praterium: "", perfekt: "" },
  },
  {
    wrt: {
      wort: "Fakultät",
      plural: "Fakultäten",
      prefix: "",
      suffix: "",
      artikel: "die",
    },
    fall: {
      Dativobjekt: "",
      Akkusativobjekt: "",
      Reflexivpronomen: "",
      Other: "",
    },
    status: {
      Deklination: "Deklination",
      Zertifikat: "C1",
      Substantiv: "Substantiv",
      Adjektiv: "",
      Superlativ: "",
      Komparativ: "",
      Plural: "-en",
      Positiv: "",
      Genus: "feminin",
      gesteigert: "",
      regelmäßige: "regelmäßig",
      Artikel: "",
      starke: "",
      Pronomen: "",
      Other: "",
    },
    theme: "",
    source: "",
    main_Html: "die <b><i></i>Fakultät<i></i></b>",
    main_Sound:
      "https://www.verbformen.de/deklination/substantive/grundform/der_Fakulta3t.mp3",
    sub_Html: "die <b><i></i>Fakultät<i>en</i></b>",
    sub_Sound:
      "https://www.verbformen.de/deklination/substantive/stammformen/der_Fakulta3t.mp3",
    lang_TR: " ",
    lang_DE: "",
    tbl: { prasens: "", praterium: "", perfekt: "" },
  },
  {
    wrt: {
      wort: "Parade",
      plural: "Paraden",
      prefix: "",
      suffix: "",
      artikel: "die",
    },
    fall: {
      Dativobjekt: "",
      Akkusativobjekt: "",
      Reflexivpronomen: "",
      Other: "",
    },
    status: {
      Deklination: "Deklination",
      Zertifikat: "C2",
      Substantiv: "Substantiv",
      Adjektiv: "",
      Superlativ: "",
      Komparativ: "",
      Plural: "-en",
      Positiv: "",
      Genus: "feminin",
      gesteigert: "",
      regelmäßige: "regelmäßig",
      Artikel: "",
      starke: "",
      Pronomen: "",
      Other: "",
    },
    theme: "",
    source: "",
    main_Html: "die <b><i></i>Parade<i></i></b>",
    main_Sound:
      "https://www.verbformen.de/deklination/substantive/grundform/der_Parade.mp3",
    sub_Html: "die <b><i></i>Parade<i>n</i></b>",
    sub_Sound:
      "https://www.verbformen.de/deklination/substantive/stammformen/der_Parade.mp3",
    lang_TR: "",
    lang_DE:
      "festliche, feierliche Aufstellung, Vorbeimarsch, Zurschaustellung, Präsentation; allgemein Abwehr von Bällen, Schlägen, Stichen und Ähnlichem; Defilee",
    tbl: { prasens: "", praterium: "", perfekt: "" },
  },
  {
    wrt: {
      wort: "Publikum",
      plural: "Publikums",
      prefix: "",
      suffix: "",
      artikel: "das",
    },
    fall: {
      Dativobjekt: "",
      Akkusativobjekt: "",
      Reflexivpronomen: "",
      Other: "",
    },
    status: {
      Deklination: "Deklination",
      Zertifikat: "B1",
      Substantiv: "Substantiv",
      Adjektiv: "",
      Superlativ: "",
      Komparativ: "",
      Plural: "-",
      Positiv: "",
      Genus: "neutral",
      gesteigert: "",
      regelmäßige: "regelmäßig",
      Artikel: "",
      starke: "",
      Pronomen: "",
      Other: "",
    },
    theme: "",
    source: "",
    main_Html: "das <b><i></i>Publikum<i></i></b>",
    main_Sound:
      "https://www.verbformen.de/deklination/substantive/grundform/der_Publikum.mp3",
    sub_Html: "die -",
    sub_Sound:
      "https://www.verbformen.de/deklination/substantive/stammformen/der_Publikum.mp3",
    lang_TR: "",
    lang_DE:
      "Bezeichnung für die Öffentlichkeit, sowie für die Gesamtheit der Zuschauer, Zuhörer, Besucher; Auditorium; Besucher; Hörerschaft; Teilnehmer; Zuhörer",
    tbl: { prasens: "", praterium: "", perfekt: "" },
  },
  {
    wrt: {
      wort: "Altertum",
      plural: "Altertums",
      prefix: "",
      suffix: "",
      artikel: "das",
    },
    fall: {
      Dativobjekt: "",
      Akkusativobjekt: "",
      Reflexivpronomen: "",
      Other: "",
    },
    status: {
      Deklination: "Deklination",
      Zertifikat: "C2",
      Substantiv: "Substantiv",
      Adjektiv: "",
      Superlativ: "",
      Komparativ: "",
      Plural: "-",
      Positiv: "",
      Genus: "neutral",
      gesteigert: "",
      regelmäßige: "regelmäßig",
      Artikel: "",
      starke: "",
      Pronomen: "",
      Other: "",
    },
    theme: "",
    source: "",
    main_Html: "das <b><i></i>Altertum<i></i></b>",
    main_Sound:
      "https://www.verbformen.de/deklination/substantive/grundform/der_Altertum.mp3",
    sub_Html: "die -",
    sub_Sound:
      "https://www.verbformen.de/deklination/substantive/stammformen/der_Altertum.mp3",
    lang_TR: "",
    lang_DE:
      "Epoche der Geschichtsschreibung in Eurasien; ein aus alten Zeiten stammender Gegenstand",
    tbl: { prasens: "", praterium: "", perfekt: "" },
  },
  {
    wrt: {
      wort: "Tasche",
      plural: "Taschen",
      prefix: "",
      suffix: "",
      artikel: "die",
    },
    fall: {
      Dativobjekt: "",
      Akkusativobjekt: "",
      Reflexivpronomen: "",
      Other: "",
    },
    status: {
      Deklination: "Deklination",
      Zertifikat: "A1",
      Substantiv: "Substantiv",
      Adjektiv: "",
      Superlativ: "",
      Komparativ: "",
      Plural: "-en",
      Positiv: "",
      Genus: "feminin",
      gesteigert: "",
      regelmäßige: "regelmäßig",
      Artikel: "",
      starke: "",
      Pronomen: "",
      Other: "",
    },
    theme: "",
    source: "",
    main_Html: "die <b><i></i>Tasche<i></i></b>",
    main_Sound:
      "https://www.verbformen.de/deklination/substantive/grundform/der_Tasche.mp3",
    sub_Html: "die <b><i></i>Tasche<i>n</i></b>",
    sub_Sound:
      "https://www.verbformen.de/deklination/substantive/stammformen/der_Tasche.mp3",
    lang_TR: "cep, çanta",
    lang_DE: "",
    tbl: { prasens: "", praterium: "", perfekt: "" },
  },
];
