
var newWort = {
  wrt: {
    wort: "",
    plural: "",
    prefix: "",
    suffix: "",
    artikel: "",
  },
  fall: {
    Dativobjekt: "",
    Akkusativobjekt: "",
    Reflexivpronomen: "",
    Other:"",
    wechsel: [
      "'an'",
      "'in'",
      "'über'",
      "'auf'",
      "'neben'",
      "'hinter'",
      "'unter'",
      "'vor'",
    ],
  },
  status: {
    Deklination: "",
    Zertifikat: "",
    Substantiv: "",
    Adjektiv: "",
    Plural: "",
    Positiv: "",
    Genus:"",
    gesteigert: "",
    Komparativ: "",
    regelmäßige:"",
    Artikel:"",
    starke:"",
    Pronomen:"",
    Other: "",
  },
  theme: "",
  source: "",
  main_Html: "",
  main_Sound: "",
  sub_Html: "",
  sub_Sound: "",
  lang_TR: "",
  prasensTbl: "",
  prateriumTbl: "",
  perfektTbl: "",
};